### ISSUE TITLE
Fix PM25 layer time discrepancy

### ISSUE THREAD

**Issue by GAO8A** [CANUEhub/SmoKE-App#1]
Currently the timestamp on the player reflects local time and the hour value rounds to the cieling limit (next hour) we need to change to UTC and round down.

**Comment by CANUEjsyer** [comment]
Reopened for Priya to investigate if automated PM2.5 extractions match the WMS

**Comment by CANUEjsyer** [comment]
Priya doing one final check on http://smokeinfo.ca/openlayers

**Comment by CANUEjsyer** [comment]
Priya has investigated alongside Rick. Perfect alignment with MSC Animet
