### ISSUE TITLE
General - Screen resolution

### ISSUE THREAD

**Issue by CANUEjsyer** [CANUEhub/SmoKE-App#10]
Screen resolution / screen size issues

**Comment by GAO8A** [comment]
Closing this issue as fixed. The user experiencing this issue had a 1920x1080 screen however had there screen scaled to 150% instead of 100% (for readability reason). 


![desktop_scaling](https://github.com/CANUEhub/SmoKE-App/assets/8060908/40302caf-4a3e-46ea-911b-713abf67ed71)
