### ISSUE TITLE
Historical - AQHI long-term average not rounding

### ISSUE THREAD

**Issue by CANUEjsyer** [CANUEhub/SmoKE-App#21]
Hi Rick, on the historical map, I chose AQHI and any year or community. I see that the long-term average is rounding to the first decimal place, but in the database when I run the query the value is rounding to the nearest integer (no decimal places). As a reminder, here is the query for AQHI: 

SELECT * FROM smoke.smoke_hist_aqhi
WHERE commid = 490 -- community ID
AND hcayear = 2020 -- year
AND haayear = 2020 -- year
AND haacanyear = 2020 -- year

![image](https://github.com/CANUEhub/SmoKE-App/assets/119965315/da645b71-29da-4b22-8d2e-9646621c56d0)

**Comment by GAO8A** [comment]
Fixed with https://github.com/CANUEhub/SmoKE-App/commit/94cf15147ccb3d79167a17b3147c52ae92958f12

**Comment by GAO8A** [comment]
Fixed with https://github.com/CANUEhub/SmoKE-App/commit/94cf15147ccb3d79167a17b3147c52ae92958f12
